# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the auto-deploy-master branch
on:
  push:
    branches: [ auto-deploy-master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions@0.1.2
      with:
        # The version of the gcloud SDK to be installed.  Example: 275.0.0
        version: # optional, default is 275.0.0
        # The service account email which will be used for authentication.
        service_account_email: # optional
        # The service account key which will be used for authentication.
        service_account_key: ${{secrets.GCLOUD_SERVICE_ACCOUNT_KEY}}

    # Run the restart script in the Gcloud ssh session
    - name: Run restart script
      env: ${{secrets.TEST_TOKEN}}
      run: ./scripts/restart-bot.sh